name: Testing

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - mystring: name1
            mybool: false
          - mystring: name2
            mybool: true
    env:
      PREFIX: foo-${{ matrix.mybool }}_bar-${{ matrix.mybool }}

    steps:
    - name: Check if name1
      run: echo ${{ matrix.mystring }} ${{ matrix.mybool }}
      if: matrix.mystring == 'name1'

    - name: Check if bool
      run: echo ${{ matrix.mystring }} ${{ matrix.mybool }}
      if: matrix.mybool == true

    - name: Run always
      run: |
        mkdir temp
        echo " == ${{ env.PREFIX }} =="
        echo ${{ matrix.mystring }} ${{ matrix.mybool }}


